/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
}


repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "com.elatec"
version = "1.0"
description = "mcm-mobile-badge-sdk"

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = project.group.toString()
            artifactId = project.name
            version = project.version.toString()

            artifact(file("mcm-mobile-badge-sdk.aar")) {
                extension = "aar"
            }

            pom {
                name.set(project.name)
                description.set(project.description)
            }
        }
    }
    repositories {
        mavenLocal()
    }
}
